language: node_js

node_js:
- '8'

cache:
  directories:
  - node_modules

install:
  - npm

script:
  - npm test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
